/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/20/22, 9:43 PM' 
 * Generated by 'Bansal' 
 * Generated on server 'DESKTOP-BQNJOTM.HSD1.CT.COMCAST.NET' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36' 
 * Generated on web client 'http://localhost:60420/main?locale=en_US&zone=GMT-05%253A00&sutoken=%257BC7B5ED6F-E823-4011-B77E-062F92790172%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.CLIMATE_AVG out=Work.preProcessedData;
	by date;
run;

proc arima data=Work.preProcessedData plots
     (only)=(series(acf corr crosscorr) residual(corr normal) 
		forecast(forecast forecastonly) ) out=work.out0001;
	identify var=meantemp crosscorr=(humidity wind_speed );
	estimate p=(1 2 3) q=(2) input=(humidity wind_speed) method=ML 
		outest=work.outest0001 outstat=work.outstat0001;
	forecast lead=52 back=52 alpha=0.05 id=date interval=week printall;
	run;
quit;

 %accuracy(indsn=WORK.outstat0001 timeid=date, series=meantemp,  
    numholdback=&nhold); */
/* %accuracy(indsn=work.ARMAX1_forecast, timeid=date, series=SALES4,  */
/*     numholdback=&nhold); */
    
proc delete data=Work.preProcessedData;
run;