/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/27/22, 2:33 PM' 
 * Generated by 'Bansal' 
 * Generated on server 'DESKTOP-BQNJOTM' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36' 
 * Generated on web client 'http://localhost:50660/main?locale=en_US&zone=GMT-05%253A00&sutoken=%257B2559A48F-139F-4978-88A6-3A6F3B17F266%257D&openfile=D%253A%255CMsbapm%255CSpring%252022%255CData%2520Mining%255CTest%255CTime%2520Series%2520Exploration.ctk' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.CLIMATE_AVG out=Work.preProcessedData;
	by date;
run;

proc timeseries data=Work.preProcessedData seasonality=52 plots=(series 
		histogram cycles corr wn decomp tc sc ic) crossplots=(series ccf) 
		print=(seasons decomp);
	id date interval=week;
	var meantemp / accumulate=none transform=none dif=0 sdif=0;
	crossvar wind_speed / accumulate=none transform=none dif=0 sdif=0;
	crossvar humidity / accumulate=none transform=none dif=0 sdif=0;
	crossvar meanpressure / accumulate=none transform=none dif=0 sdif=0;
	decomp tc seasonal irregular / mode=multoradd;
	ods exclude CCFNORMPlot;
run;

/* Unit root test analysis */
proc arima data=Work.preProcessedData plots=none;
	ods select StationarityTests;
	identify var=meantemp stationarity=(adf=2);
	run;
quit;

proc delete data=Work.preProcessedData;
run;